### PR TITLE
Replace video element with static image on Mobile Safari.

### LINKED ISSUE #430: Tile with a video should not show "play" button on mobile
upload

### PR DESCRIPTION
**Pull request by DFurnes**
# Changes
 - Fixes #430. On Mobile Safari, replace any `video` tags within a tile with a static `img` based on their poster or fallback image.

For review: @DoSomething/front-end 

# Discussion
I think this is an appropriate scenario for browser-sniffing, since it's not really a "feature" we're trying to detect but an idiosyncrasy with how a particular browser treats a standard tag. Thoughts?

### CODE REVIEW

**Comment by sbsmith86** [comment]
Looks good! Also, agreed with browser-sniffing for this.

**Comment by weerd** [comment]
So it's only an idiosyncrasy in a very particular context which applies to us specifically. In any other scenario where video is used on mobile safari, having a click to play makes sense so you don't force a download of the video to an unsuspecting mobile user. It just *happens* to affect us on the homepage, because our tiles are clickable....

Could there potentially be something we could do with the video controls API with JavaScript. I know you can tap into video controls and affect the visual display of the video controls... maybe that could lead us on the path to a better solution and avoid browser-sniffing? Not sure...

**Comment by DFurnes** [comment]
I agree that the non-standard behavior is a usability win for users, but I think it's also a bit questionable that Safari ignores the spec for disabling controls on a `video` element. Ideally they would only ignore the `autoplay` option.

iOS 8 adds a proprietary CSS pseudo-element that we can target, but that still leaves a visual gotcha for iOS 7 users. I'm all for other solutions, but having trouble finding good ones.

**Comment by weerd** [comment]
With our powers combined...

**Comment by weerd** [comment]
we can hopefully find a solution! Oh yeah, and...

**Pull request closed without merging**
